"use client";
import { useCallback,useEffect,useState } from "react";
import { CalendarDays, Check, ChevronLeft, Plus, Share2, Trash2, Users } from "lucide-react";
import { useParams } from "next/navigation";
import { createClient } from "@/lib/supabase/client";
import { shareTextNatively } from "@/lib/native/share";
import { googleCalendarUrl } from "@/lib/google-calendar";

type Plan={id:string;name:string;kind:string;description:string};
type Member={user_id:string;display_name:string;role:string};
type Item={id:string;item_type:string;title:string;description:string;start_date:string|null;due_date:string|null;start_time:string|null;due_time:string|null;status:string;assigned_to:string|null;recurrence?:{frequency?:string;dayOfWeek?:string;until?:string}|null};
export default function SharedPlanPage(){
 const {id}=useParams<{id:string}>(); const [plan,setPlan]=useState<Plan|null>(null),[items,setItems]=useState<Item[]>([]),[title,setTitle]=useState(""),[date,setDate]=useState(""),[type,setType]=useState("task"),[busy,setBusy]=useState(false),[error,setError]=useState(""),[members,setMembers]=useState<Member[]>([]);
 const load=useCallback(async()=>{const db=createClient();const [p,i,m]=await Promise.all([db.from("shared_plans").select("id,name,kind,description").eq("id",id).single(),db.from("shared_plan_items").select("id,item_type,title,description,start_date,due_date,start_time,due_time,status,assigned_to,recurrence").eq("plan_id",id).neq("status","cancelled").order("created_at"),db.rpc("shared_plan_member_directory",{p_plan:id})]);if(p.error){setError("This shared plan is unavailable.");return;}setPlan(p.data as Plan);setItems((i.data||[]) as Item[]);setMembers((m.data||[]) as Member[]);},[id]);
 useEffect(()=>{load();},[load]);
 async function add(){if(!title.trim()||!date)return;setBusy(true);const db=createClient();const {data:{user}}=await db.auth.getUser();if(!user){location.assign(`/login?next=${encodeURIComponent("/shared/"+id)}`);return;}const due=type==="task"||type==="deadline";const {error:e}=await db.from("shared_plan_items").insert({plan_id:id,creator_id:user.id,item_type:type,title:title.trim(),due_date:due?date:null,start_date:due?null:date,all_day:true,timezone:Intl.DateTimeFormat().resolvedOptions().timeZone||"UTC"});if(e)setError(e.message);else{setTitle("");setDate("");await load();}setBusy(false);}
 async function complete(item:Item){const db=createClient();await db.from("shared_plan_items").update({status:item.status==="completed"?"open":"completed"}).eq("id",item.id);await load();}
 async function remove(item:Item){const db=createClient();await db.from("shared_plan_items").update({status:"cancelled"}).eq("id",item.id);await load();}
 async function assign(item:Item,userId:string){const db=createClient();const {error:e}=await db.rpc("assign_shared_item",{p_item:item.id,p_user:userId||null});if(e)setError(e.message);else await load();}
 function addToCalendar(item:Item){const d=item.start_date||item.due_date;if(!d)return;const event={title:item.title,description:item.description||"",startDate:d,endDate:d,startTime:item.start_time?String(item.start_time).slice(0,5):item.due_time?String(item.due_time).slice(0,5):"",endTime:"",allDay:!item.start_time&&!item.due_time,timezone:Intl.DateTimeFormat().resolvedOptions().timeZone||"UTC",location:"",confidence:1,confidenceReason:"Shared Zest plan",sourceText:"",category:"event" as const};location.assign(googleCalendarUrl(event,event.timezone));}
 async function invite(){if(!plan)return;const db=createClient();const {data,error:e}=await db.rpc("create_shared_invite",{p_plan:id,p_email:null,p_role:"editor"});if(e)return setError(e.message);const url=`${location.origin}/share/${data}`;if(await shareTextNatively({title:plan.name,text:`Join “${plan.name}” on Zest Snap: ${url}`,url}))return;await navigator.clipboard.writeText(url);setError("Invite link copied.");}
 return <main className="sharedPlanPage"><div className="sharedPlanWrap"><a className="settingsBack" href="/app?view=shared"><ChevronLeft/> Shared</a>{plan&&<><header className="sharedPlanHeader"><div><span className="eyebrow">{plan.kind.toUpperCase()}</span><h1>{plan.name}</h1><p>{plan.kind==="meals"?"A simple shared meal plan.":plan.kind==="timetable"?"A timetable everyone can keep up to date.":"One plan, kept up to date for everyone."}</p></div><button className="button alt small" onClick={invite}><Share2/> Invite</button></header><section className="sharedComposer"><div className="sharedComposerFields"><select value={type} onChange={e=>setType(e.target.value)}><option value="task">To-Do</option><option value="event">Event</option><option value="deadline">Deadline</option>{plan.kind==="meals"&&<option value="meal">Meal</option>}</select><input value={title} onChange={e=>setTitle(e.target.value)} placeholder={plan.kind==="meals"?"What are you eating?":"Add something…"}/><input type="date" value={date} onChange={e=>setDate(e.target.value)}/></div><button className="button" disabled={busy||!title.trim()||!date} onClick={add}><Plus/> Add</button></section><section className="sharedPlanItems">{items.length?items.map(item=><article className={"sharedPlanItem "+(item.status==="completed"?"completed":"")} key={item.id}><button className="todoCheck" onClick={()=>complete(item)} aria-label="Toggle done">{item.status==="completed"&&<Check/>}</button><div><b>{item.title}</b><small>{item.due_date||item.start_date}{item.recurrence?.frequency==="weekly"?` · every ${item.recurrence.dayOfWeek||"week"}${item.recurrence.until?` until ${item.recurrence.until}`:""}`:item.item_type!=="event"?` · ${item.item_type}`:""}</small>{members.length>1&&item.item_type!=="event"&&item.item_type!=="meal"&&<select className="sharedAssignee" value={item.assigned_to||""} onChange={e=>assign(item,e.target.value)}><option value="">Unassigned</option>{members.map(m=><option key={m.user_id} value={m.user_id}>{m.display_name}</option>)}</select>}</div>{(item.start_date||item.due_date)&&<button className="iconButton" onClick={()=>addToCalendar(item)} aria-label="Add to my calendar"><CalendarDays/></button>}<button className="iconButton" onClick={()=>remove(item)} aria-label="Remove"><Trash2/></button></article>):<div className="sharedEmpty compact"><Users/><h2>Nothing here yet</h2><p>Add the first item, then invite the people you want to plan with.</p></div>}</section></>}{error&&<p className="supportFormError">{error}</p>}</div></main>;
}
