"use client";
import {useEffect,useMemo,useState} from "react";
import {Bell,CalendarDays,Check,CheckCircle2,ChevronLeft,ChevronRight,Clock3,Pencil,Plus,Trash2,X} from "lucide-react";
import {getDataProvider} from "@/lib/data";
import {monthGrid,plannerReferenceDate,plannerStatus,todayDate,type PlannerItem,type PlannerItemType,type ReminderDraft,type ReminderPreset} from "@/lib/planner";
import {PlannerStore} from "@/lib/planner-store";
import {cancelReminder,createReminder,enablePushNotifications,getNotificationState,listReminders,markReminderHandled,snoozeReminder,type NotificationState,type ReminderRecord} from "@/lib/reminders";
type Tab="today"|"upcoming"|"calendar"|"reminders"; type CalendarAction="plan"|"remind"|null; type Props={initialTab?:"today"|"upcoming";onNotice?:(kind:"success"|"error",message:string)=>void};
function emptyItem(timezone:string):PlannerItem{const today=todayDate(timezone),now=new Date().toISOString();return{id:crypto.randomUUID(),type:"event",title:"",description:"",startDate:today,endDate:today,startTime:"",endTime:"",dueDate:today,dueTime:"",allDay:true,timezone,location:"",status:"open",source:"manual",createdAt:now,updatedAt:now};}
export default function PlannerView({initialTab="today",onNotice}:Props){
 const[store,setStore]=useState<PlannerStore|null>(null),[items,setItems]=useState<PlannerItem[]>([]),[reminders,setReminders]=useState<ReminderRecord[]>([]),[tab,setTab]=useState<Tab>(initialTab),[locale,setLocale]=useState("en"),[timezone,setTimezone]=useState("UTC"),[selectedDate,setSelectedDate]=useState(""),[month,setMonth]=useState(()=>{const d=new Date();return{year:d.getFullYear(),month:d.getMonth()+1}}),[editing,setEditing]=useState<PlannerItem|null>(null),[reminderItem,setReminderItem]=useState<PlannerItem|null>(null),[busy,setBusy]=useState(false),[calendarAction,setCalendarAction]=useState<CalendarAction>(null),[standaloneReminder,setStandaloneReminder]=useState<PlannerItem|null>(null),[notificationState,setNotificationState]=useState<NotificationState>("available"),[reminderFilter,setReminderFilter]=useState<"all"|"today"|"upcoming"|"overdue">("all");
 const notice=(k:"success"|"error",m:string)=>onNotice?.(k,m); async function refresh(s=store){if(!s)return;const[i,r,n]=await Promise.all([s.load(),listReminders(),getNotificationState()]);setItems(i);setReminders(r);setNotificationState(n);}
 useEffect(()=>{let alive=true;Promise.all([PlannerStore.create(),getDataProvider().then(p=>p.loadProfile())]).then(async([s,p])=>{if(!alive)return;setStore(s);setLocale(p.locale||navigator.language);setTimezone(p.timezone||Intl.DateTimeFormat().resolvedOptions().timeZone||"UTC");setSelectedDate(todayDate(p.timezone||"UTC"));const cached=s.loadCached();if(cached.length)setItems(cached);await refresh(s);}).catch(()=>notice("error","Planner could not be loaded."));return()=>{alive=false};},[]); // eslint-disable-line react-hooks/exhaustive-deps
 useEffect(()=>{const q=new URLSearchParams(window.location.search),action=q.get("reminderAction"),id=q.get("reminderId");if(action!=="snooze"||!id)return;snoozeReminder(id,15).then(()=>{notice("success","Reminder snoozed for 15 minutes.");setTab("reminders");return refresh();}).catch(e=>notice("error",e instanceof Error?e.message:"Reminder could not be snoozed.")).finally(()=>{q.delete("reminderAction");q.delete("reminderId");const next=window.location.pathname+(q.size?"?"+q.toString():"");window.history.replaceState({}, "", next);});},[]); // eslint-disable-line react-hooks/exhaustive-deps
 const today=useMemo(()=>todayDate(timezone),[timezone]),visible=useMemo(()=>{const filtered=tab==="today"?items.filter(x=>plannerReferenceDate(x)===today&&x.status!=="cancelled"):tab==="upcoming"?items.filter(x=>plannerReferenceDate(x)>=today&&x.status!=="cancelled"):tab==="calendar"?items.filter(x=>plannerReferenceDate(x)===selectedDate&&x.status!=="cancelled"):[];return filtered.sort((a,b)=>(plannerReferenceDate(a)+(a.startTime||a.dueTime||"")).localeCompare(plannerReferenceDate(b)+(b.startTime||b.dueTime||"")));},[items,tab,today,selectedDate]),calendar=useMemo(()=>monthGrid(month.year,month.month,locale,timezone),[month,locale,timezone]),marked=useMemo(()=>new Set(items.filter(x=>x.status!=="cancelled").map(plannerReferenceDate)),[items]);
 const act=async(fn:()=>Promise<void>)=>{if(busy)return;setBusy(true);try{await fn();await refresh();}catch(e){notice("error",e instanceof Error?e.message:"Planner action failed.");}finally{setBusy(false);}};
 return <section className="plannerRoot"><div className="plannerHero"><div><div className="eyebrow">PLANNER</div><h1>Your planner</h1><p>Events, tasks, deadlines and reminders — organised in Zest.</p></div><div className="plannerHeroActions"><button className="plannerReminderButton" onClick={()=>setTab("reminders")} aria-label="Open reminders"><Bell/>{reminders.filter(r=>["pending","sent"].includes(r.status)).length>0&&<span>{reminders.filter(r=>["pending","sent"].includes(r.status)).length}</span>}</button><button className="plannerFab" onClick={()=>setEditing(emptyItem(timezone))} aria-label="Create Planner item"><Plus/></button></div></div>
 {tab!=="reminders"&&<div className="plannerTabs" role="tablist">{(["today","upcoming","calendar"] as Tab[]).map(v=><button role="tab" aria-selected={tab===v} key={v} className={tab===v?"active":""} onClick={()=>setTab(v)}>{v[0].toUpperCase()+v.slice(1)}</button>)}</div>}
 {tab==="calendar"&&<div className="plannerCalendar"><div className="calendarTop"><button onClick={()=>setMonth(m=>m.month===1?{year:m.year-1,month:12}:{year:m.year,month:m.month-1})} aria-label="Previous month"><ChevronLeft/></button><strong>{new Intl.DateTimeFormat(locale,{month:"long",year:"numeric",timeZone:"UTC"}).format(new Date(Date.UTC(month.year,month.month-1,15)))}</strong><button onClick={()=>setMonth(m=>m.month===12?{year:m.year+1,month:1}:{year:m.year,month:m.month+1})} aria-label="Next month"><ChevronRight/></button></div><button className="todayShortcut" onClick={()=>{const d=new Date();setMonth({year:d.getFullYear(),month:d.getMonth()+1});setSelectedDate(today)}}>Today</button><div className="weekdayRow">{calendar.weekdayLabels.map((x,i)=><span key={i}>{x}</span>)}</div><div className="monthGrid">{calendar.cells.map(c=><button key={c.date} className={`${c.inMonth?"":"outside"} ${selectedDate===c.date?"selected":""}`} onClick={()=>{setSelectedDate(c.date);setCalendarAction("plan")}}><span>{Number(c.date.slice(-2))}</span>{marked.has(c.date)&&<i/>}</button>)}</div></div>}
 {tab!=="reminders"&&<div className="plannerList">{!visible.length&&<div className="plannerEmpty"><CalendarDays/><b>{tab==="today"?"Nothing planned for today":tab==="calendar"?"Nothing on this day":"No upcoming items"}</b><span>Add something manually or save an item after a scan.</span><button className="button alt" onClick={()=>setEditing(emptyItem(timezone))}>Add to Planner</button></div>}{visible.map(item=><article className={`plannerCard ${plannerStatus(item)}`} key={item.id}>{(item.type==="task"||item.type==="deadline")&&<button className="completeButton" onClick={()=>act(()=>store!.setCompleted(item.id,item.status!=="completed").then(()=>undefined))}>{item.status==="completed"?<CheckCircle2/>:<Check/>}</button>}<div className="plannerCardBody"><div className="plannerCardTop"><span>{item.type}</span><em>{plannerStatus(item)}</em></div><h3>{item.title}</h3><p><Clock3/> {new Intl.DateTimeFormat(locale,{dateStyle:"medium",timeZone:"UTC"}).format(new Date(plannerReferenceDate(item)+"T12:00:00Z"))}</p><div className="plannerCardActions"><button onClick={()=>setReminderItem(item)}><Bell/> Reminder</button><button onClick={()=>setEditing(item)}><Pencil/> Edit</button><button onClick={()=>act(()=>store!.remove(item.id))}><Trash2/> Delete</button></div></div></article>)}</div>}
 {tab==="reminders"&&<RemindersPage reminders={reminders} items={items} locale={locale} timezone={timezone} filter={reminderFilter} setFilter={setReminderFilter} notificationState={notificationState} busy={busy} onBack={()=>setTab("today")} onEnable={()=>act(async()=>{await enablePushNotifications();setNotificationState(await getNotificationState());notice("success","Notifications are on for this device.")})} onHandled={id=>act(()=>markReminderHandled(id))} onSnooze={id=>act(()=>snoozeReminder(id,15))} onCancel={id=>act(()=>cancelReminder(id))}/>} 
 {calendarAction&&<div className="plannerOverlay"><section className="plannerSheet compact calendarActionSheet"><div className="sheetTop"><div><h2>{new Intl.DateTimeFormat(locale,{dateStyle:"long",timeZone:"UTC"}).format(new Date(selectedDate+"T12:00:00Z"))}</h2><span className="sheetHint">What would you like to add?</span></div><button className="iconButton" onClick={()=>setCalendarAction(null)}><X/></button></div><div className="calendarActionChoices"><button onClick={()=>{const i=emptyItem(timezone);i.startDate=selectedDate;i.endDate=selectedDate;i.dueDate=selectedDate;setCalendarAction(null);setEditing(i)}}><CalendarDays/><b>Plan something</b><span>Add an event, task or deadline.</span></button><button onClick={()=>{const i=emptyItem(timezone);i.type="reminder";i.startDate=selectedDate;i.endDate=selectedDate;i.dueDate=selectedDate;i.title="Reminder";setCalendarAction(null);setStandaloneReminder(i)}}><Bell/><b>Set a reminder</b><span>Choose a time and get notified.</span></button></div></section></div>}
 {editing&&<Editor item={editing} busy={busy} onClose={()=>setEditing(null)} onSave={i=>act(async()=>{await store!.upsert(i);setEditing(null);notice("success","Saved to Planner.")})}/>}
 {standaloneReminder&&<Reminder item={standaloneReminder} busy={busy} onClose={()=>setStandaloneReminder(null)} onSave={d=>act(async()=>{await store!.upsert(standaloneReminder);const r=await createReminder(standaloneReminder,d);setStandaloneReminder(null);notice("success",r.backgroundDelivery?"Reminder scheduled.":"Reminder saved on this device.")})}/>}
 {reminderItem&&<Reminder item={reminderItem} busy={busy} onClose={()=>setReminderItem(null)} onSave={d=>act(async()=>{const r=await createReminder(reminderItem,d);setReminderItem(null);notice("success",r.backgroundDelivery?"Reminder scheduled.":"Reminder saved on this device.")})}/>}</section>;
}
function RemindersPage({reminders,items,locale,timezone,filter,setFilter,notificationState,busy,onBack,onEnable,onHandled,onSnooze,onCancel}:{reminders:ReminderRecord[];items:PlannerItem[];locale:string;timezone:string;filter:"all"|"today"|"upcoming"|"overdue";setFilter:(v:"all"|"today"|"upcoming"|"overdue")=>void;notificationState:NotificationState;busy:boolean;onBack:()=>void;onEnable:()=>void;onHandled:(id:string)=>void;onSnooze:(id:string)=>void;onCancel:(id:string)=>void;}){
 const now=new Date(),today=todayDate(timezone),active=reminders.filter(r=>r.status!=="cancelled"&&r.status!=="handled"),itemFor=(r:ReminderRecord)=>items.find(i=>i.id===r.plannerItemId);
 const dateKey=(r:ReminderRecord)=>new Intl.DateTimeFormat("en-CA",{year:"numeric",month:"2-digit",day:"2-digit",timeZone:timezone}).format(new Date(r.scheduledAt));
 const filtered=active.filter(r=>filter==="all"||(filter==="today"&&dateKey(r)===today)||(filter==="upcoming"&&new Date(r.scheduledAt)>=now&&dateKey(r)!==today)||(filter==="overdue"&&new Date(r.scheduledAt)<now));
 const todayRows=filtered.filter(r=>dateKey(r)===today),otherRows=filtered.filter(r=>dateKey(r)!==today);
 const row=(r:ReminderRecord)=>{const item=itemFor(r),when=new Intl.DateTimeFormat(locale,{dateStyle:dateKey(r)===today?undefined:"medium",timeStyle:"short",timeZone:timezone}).format(new Date(r.scheduledAt));return <article className="reminderCard" key={r.id}><div className="reminderCardIcon"><Bell/></div><div className="reminderCardCopy"><b>{item?.title||r.label||"Reminder"}</b><span><CalendarDays/> {dateKey(r)===today?"Today, ": ""}{when}</span><span><Clock3/> {r.offsetMinutes===0?"At time":r.offsetMinutes?formatOffset(r.offsetMinutes)+" before":"Scheduled reminder"}</span></div><div className="reminderCardMenu"><button onClick={()=>onSnooze(r.id)} disabled={busy} aria-label="Snooze 15 minutes">•••</button><button className="reminderCheck" onClick={()=>onHandled(r.id)} disabled={busy} aria-label="Mark reminder done"><Check/></button></div></article>};
 return <div className="remindersStandalone"><div className="remindersTitle"><button className="reminderBack" onClick={onBack} aria-label="Back to Planner"><ChevronLeft/></button><div><h2>Reminders</h2><p>All your upcoming reminders and notifications in one place.</p></div></div>
 <div className="reminderFilters">{(["all","today","upcoming","overdue"] as const).map(v=><button key={v} className={filter===v?"active":""} onClick={()=>setFilter(v)}>{v[0].toUpperCase()+v.slice(1)}</button>)}</div>
 <div className={"notificationStatus "+notificationState}><Bell/><div><b>{notificationState==="enabled"?"Notifications on":notificationState==="blocked"?"Notifications blocked":notificationState==="unsupported"?"Notifications unavailable":"Background notifications"}</b><span>{notificationState==="enabled"?"Zest can notify you on this device.":notificationState==="blocked"?"Allow notifications in your browser or phone settings.":notificationState==="unsupported"?"This browser does not support background reminders.":"Get reminders even when Zest isn't open."}</span></div>{notificationState==="available"&&<button className="button alt" onClick={onEnable} disabled={busy}>Enable</button>}{notificationState==="enabled"&&<CheckCircle2/>}</div>
 {!filtered.length?<div className="plannerEmpty reminderEmpty"><Bell/><b>{filter==="all"?"No reminders yet":`No ${filter} reminders`}</b><span>Your scheduled reminders will appear here.</span></div>:<>{todayRows.length>0&&<section className="reminderGroup"><h3>Today <span>{todayRows.length}</span></h3>{todayRows.map(row)}</section>}{otherRows.length>0&&<section className="reminderGroup"><h3>{filter==="overdue"?"Overdue":"Upcoming"} <span>{otherRows.length}</span></h3>{otherRows.map(row)}</section>}</>}
 </div>;
}
function formatOffset(minutes:number){if(minutes%10080===0)return `${minutes/10080} week${minutes===10080?"":"s"}`;if(minutes%1440===0)return `${minutes/1440} day${minutes===1440?"":"s"}`;if(minutes%60===0)return `${minutes/60} hour${minutes===60?"":"s"}`;return `${minutes} min`;}
function Editor({item,busy,onClose,onSave}:{item:PlannerItem;busy:boolean;onClose:()=>void;onSave:(i:PlannerItem,d?:ReminderDraft)=>void}){
 const[d,setD]=useState(item),[reminder,setReminder]=useState<"none"|ReminderPreset>(item.title?"none":item.allDay?"none":"at_time"),task=d.type==="task"||d.type==="deadline",patch=(p:Partial<PlannerItem>)=>setD({...d,...p,updatedAt:new Date().toISOString()});
 const time=task?d.dueTime:d.startTime;
 const setTime=(v:string)=>patch(task?{dueTime:v}:{startTime:v});
 const tzLabel=d.timezone==="UTC"?"UTC":d.timezone.replace(/_/g," ");
 const save=()=>onSave(d,reminder==="none"?undefined:{preset:reminder});
 return <div className="plannerOverlay"><section className="plannerSheet plannerEditorCompact" role="dialog" aria-modal="true">
  <div className="sheetTop"><div><h2>{item.title?"Edit item":"Add to Planner"}</h2><span className="sheetHint">Keep the essentials here. You can edit the rest later.</span></div><button className="iconButton" onClick={onClose}><X/></button></div>
  <div className="plannerKinds">{(["event","task","deadline"] as PlannerItemType[]).map(t=><button key={t} className={d.type===t?"active":""} onClick={()=>patch({type:t,startDate:t==="task"||t==="deadline"?"":d.startDate||d.dueDate,dueDate:t==="task"||t==="deadline"?d.dueDate||d.startDate:""})}>{t}</button>)}</div>
  <label><span>Title</span><input value={d.title} onChange={e=>patch({title:e.target.value})} placeholder={task?"What needs to be done?":"What are you planning?"}/></label>
  <div className="fieldGrid compactFields"><label><span>{task?"Due date":"Start date"}</span><input type="date" value={task?d.dueDate:d.startDate} onChange={e=>patch(task?{dueDate:e.target.value}:{startDate:e.target.value,endDate:d.endDate||e.target.value})}/></label>{!d.allDay&&<label><span>Time</span><input className="timeTextInput" inputMode="numeric" maxLength={5} placeholder="08:30" value={time} onChange={e=>setTime(e.target.value.replace(/[^0-9:]/g,"").slice(0,5))}/></label>}</div>
  <label className="checkLabel"><input type="checkbox" checked={d.allDay} onChange={e=>{const allDay=e.target.checked;patch({allDay});if(!allDay&&reminder==="none")setReminder("at_time");if(allDay&&reminder==="at_time")setReminder("none");}}/> All day</label>
  <div className="plannerTimezoneRow"><div><span>Timezone</span><b>{tzLabel}</b></div><small>Uses your device/profile timezone automatically</small></div>
  <label><span>Location <small>(optional)</small></span><input value={d.location} onChange={e=>patch({location:e.target.value})} placeholder="Add a place"/></label>
  <div className="plannerReminderSelect"><div><span>Reminder</span><small>{d.allDay?"Optional alert for this date":"Get a phone notification"}</small></div><select value={reminder} onChange={e=>setReminder(e.target.value as "none"|ReminderPreset)}>
    <option value="none">None</option><option value="at_time">At time</option><option value="5m">5 min before</option><option value="15m">15 min before</option><option value="30m">30 min before</option><option value="1h">1 hour before</option><option value="1d">1 day before</option>
  </select></div>
  <label><span>Notes <small>(optional)</small></span><textarea rows={3} value={d.description} onChange={e=>patch({description:e.target.value})} placeholder="Add useful details"/></label>
  <button className="button sheetSave" disabled={busy||!d.title.trim()||(!d.allDay&&!time)} onClick={save}>{busy?"Saving…":reminder==="none"?"Save to Planner":"Save with reminder"}</button>
 </section></div>;
}
function Reminder({item,busy,onClose,onSave}:{item:PlannerItem;busy:boolean;onClose:()=>void;onSave:(d:ReminderDraft)=>void}){
 const[p,setP]=useState<ReminderDraft["preset"]>(item.type==="task"||item.type==="deadline"?"1d":"1h");
 const[custom,setCustom]=useState("");
 const[unit,setUnit]=useState<"minutes"|"hours"|"days">("hours");
 const[time,setTime]=useState("09:00");
 const number=custom.trim()===""?NaN:Number(custom);
 const multiplier=unit==="days"?1440:unit==="hours"?60:1;
 const customMinutes=Number.isFinite(number)?Math.round(number*multiplier):NaN;
 const customValid=p!=="custom"||(Number.isFinite(customMinutes)&&customMinutes>=0&&customMinutes<=525600);
 return <div className="plannerOverlay">
  <section className="plannerSheet compact reminderSheet" role="dialog" aria-modal="true" aria-labelledby="reminder-title">
   <div className="sheetTop"><div><h2 id="reminder-title">Reminder</h2><span className="sheetHint">Choose when Zest should remind you.</span></div><button className="iconButton" onClick={onClose} aria-label="Close reminder"><X/></button></div>
   <div className="reminderChoices">{([["at_time","At time"],["5m","5 min before"],["15m","15 min before"],["30m","30 min before"],["1h","1 hour before"],["1d","1 day before"],["1w","1 week before"],["custom","Custom"]] as [ReminderDraft["preset"],string][]).map(([v,l])=><button type="button" key={v} className={p===v?"active":""} onClick={()=>setP(v)}>{l}</button>)}</div>
   {item.allDay&&<label className="reminderField"><span>Reminder time</span><input type="time" value={time} onChange={e=>setTime(e.target.value)}/></label>}
   {p==="custom"&&<div className="customReminder">
    <label className="reminderField"><span>How long before?</span><input type="number" inputMode="decimal" min="0" step="1" value={custom} placeholder="Enter a number" onChange={e=>setCustom(e.target.value)}/></label>
    <label className="reminderField"><span>Unit</span><select value={unit} onChange={e=>setUnit(e.target.value as "minutes"|"hours"|"days")}><option value="minutes">Minutes</option><option value="hours">Hours</option><option value="days">Days</option></select></label>
   </div>}
   {p==="custom"&&!customValid&&custom.trim()!==""&&<p className="reminderError">Choose a reminder between 0 minutes and 365 days.</p>}
   <button className="button sheetSave" disabled={busy||!customValid} onClick={()=>onSave({preset:p,customMinutes:p==="custom"?customMinutes:undefined,allDayTime:item.allDay?time:undefined})}>Schedule reminder</button>
  </section>
 </div>;
}
