"use client";
import {useEffect,useMemo,useState} from "react";
import {Bell,CalendarDays,Check,CheckCircle2,ChevronLeft,ChevronRight,Clock3,Pencil,Plus,Trash2,X} from "lucide-react";
import {getDataProvider} from "@/lib/data";
import {monthGrid,plannerReferenceDate,plannerStatus,todayDate,type PlannerItem,type PlannerItemType,type ReminderDraft} from "@/lib/planner";
import {PlannerStore} from "@/lib/planner-store";
import {cancelReminder,createReminder,enablePushNotifications,listReminders,markReminderHandled,snoozeReminder,type ReminderRecord} from "@/lib/reminders";
type Tab="today"|"upcoming"|"calendar"|"reminders"; type CalendarAction="plan"|"remind"|null; type Props={initialTab?:"today"|"upcoming";onNotice?:(kind:"success"|"error",message:string)=>void};
function emptyItem(timezone:string):PlannerItem{const today=todayDate(timezone),now=new Date().toISOString();return{id:crypto.randomUUID(),type:"event",title:"",description:"",startDate:today,endDate:today,startTime:"",endTime:"",dueDate:today,dueTime:"",allDay:true,timezone,location:"",status:"open",source:"manual",createdAt:now,updatedAt:now};}
export default function PlannerView({initialTab="today",onNotice}:Props){
 const[store,setStore]=useState<PlannerStore|null>(null),[items,setItems]=useState<PlannerItem[]>([]),[reminders,setReminders]=useState<ReminderRecord[]>([]),[tab,setTab]=useState<Tab>(initialTab),[locale,setLocale]=useState("en"),[timezone,setTimezone]=useState("UTC"),[selectedDate,setSelectedDate]=useState(""),[month,setMonth]=useState(()=>{const d=new Date();return{year:d.getFullYear(),month:d.getMonth()+1}}),[editing,setEditing]=useState<PlannerItem|null>(null),[reminderItem,setReminderItem]=useState<PlannerItem|null>(null),[busy,setBusy]=useState(false),[calendarAction,setCalendarAction]=useState<CalendarAction>(null),[standaloneReminder,setStandaloneReminder]=useState<PlannerItem|null>(null);
 const notice=(k:"success"|"error",m:string)=>onNotice?.(k,m); async function refresh(s=store){if(!s)return;const[i,r]=await Promise.all([s.load(),listReminders()]);setItems(i);setReminders(r);}
 useEffect(()=>{let alive=true;Promise.all([PlannerStore.create(),getDataProvider().then(p=>p.loadProfile())]).then(async([s,p])=>{if(!alive)return;setStore(s);setLocale(p.locale||navigator.language);setTimezone(p.timezone||Intl.DateTimeFormat().resolvedOptions().timeZone||"UTC");setSelectedDate(todayDate(p.timezone||"UTC"));await refresh(s);}).catch(()=>notice("error","Planner could not be loaded."));return()=>{alive=false};},[]); // eslint-disable-line react-hooks/exhaustive-deps
 useEffect(()=>{const q=new URLSearchParams(window.location.search),action=q.get("reminderAction"),id=q.get("reminderId");if(action!=="snooze"||!id)return;snoozeReminder(id,15).then(()=>{notice("success","Reminder snoozed for 15 minutes.");setTab("reminders");return refresh();}).catch(e=>notice("error",e instanceof Error?e.message:"Reminder could not be snoozed.")).finally(()=>{q.delete("reminderAction");q.delete("reminderId");const next=window.location.pathname+(q.size?"?"+q.toString():"");window.history.replaceState({}, "", next);});},[]); // eslint-disable-line react-hooks/exhaustive-deps
 const today=useMemo(()=>todayDate(timezone),[timezone]),visible=useMemo(()=>{const filtered=tab==="today"?items.filter(x=>plannerReferenceDate(x)===today&&x.status!=="cancelled"):tab==="upcoming"?items.filter(x=>plannerReferenceDate(x)>=today&&x.status!=="cancelled"):tab==="calendar"?items.filter(x=>plannerReferenceDate(x)===selectedDate&&x.status!=="cancelled"):[];return filtered.sort((a,b)=>(plannerReferenceDate(a)+(a.startTime||a.dueTime||"")).localeCompare(plannerReferenceDate(b)+(b.startTime||b.dueTime||"")));},[items,tab,today,selectedDate]),calendar=useMemo(()=>monthGrid(month.year,month.month,locale,timezone),[month,locale,timezone]),marked=useMemo(()=>new Set(items.filter(x=>x.status!=="cancelled").map(plannerReferenceDate)),[items]);
 const act=async(fn:()=>Promise<void>)=>{if(busy)return;setBusy(true);try{await fn();await refresh();}catch(e){notice("error",e instanceof Error?e.message:"Planner action failed.");}finally{setBusy(false);}};
 return <section className="plannerRoot"><div className="plannerHero"><div><div className="eyebrow">PLANNER</div><h1>Your planner</h1><p>Events, tasks, deadlines and reminders — organised in Zest.</p></div><div className="plannerHeroActions"><button className="plannerReminderButton" onClick={()=>setTab("reminders")} aria-label="Open reminders"><Bell/>{reminders.filter(r=>["pending","sent"].includes(r.status)).length>0&&<span>{reminders.filter(r=>["pending","sent"].includes(r.status)).length}</span>}</button><button className="plannerFab" onClick={()=>setEditing(emptyItem(timezone))} aria-label="Create Planner item"><Plus/></button></div></div>
 {tab!=="reminders"&&<div className="plannerTabs" role="tablist">{(["today","upcoming","calendar"] as Tab[]).map(v=><button role="tab" aria-selected={tab===v} key={v} className={tab===v?"active":""} onClick={()=>setTab(v)}>{v[0].toUpperCase()+v.slice(1)}</button>)}</div>}
 {tab==="calendar"&&<div className="plannerCalendar"><div className="calendarTop"><button onClick={()=>setMonth(m=>m.month===1?{year:m.year-1,month:12}:{year:m.year,month:m.month-1})} aria-label="Previous month"><ChevronLeft/></button><strong>{new Intl.DateTimeFormat(locale,{month:"long",year:"numeric",timeZone:"UTC"}).format(new Date(Date.UTC(month.year,month.month-1,15)))}</strong><button onClick={()=>setMonth(m=>m.month===12?{year:m.year+1,month:1}:{year:m.year,month:m.month+1})} aria-label="Next month"><ChevronRight/></button></div><button className="todayShortcut" onClick={()=>{const d=new Date();setMonth({year:d.getFullYear(),month:d.getMonth()+1});setSelectedDate(today)}}>Today</button><div className="weekdayRow">{calendar.weekdayLabels.map((x,i)=><span key={i}>{x}</span>)}</div><div className="monthGrid">{calendar.cells.map(c=><button key={c.date} className={`${c.inMonth?"":"outside"} ${selectedDate===c.date?"selected":""}`} onClick={()=>{setSelectedDate(c.date);setCalendarAction("plan")}}><span>{Number(c.date.slice(-2))}</span>{marked.has(c.date)&&<i/>}</button>)}</div></div>}
 {tab!=="reminders"&&<div className="plannerList">{!visible.length&&<div className="plannerEmpty"><CalendarDays/><b>{tab==="today"?"Nothing planned for today":tab==="calendar"?"Nothing on this day":"No upcoming items"}</b><span>Add something manually or save an item after a scan.</span><button className="button alt" onClick={()=>setEditing(emptyItem(timezone))}>Add to Planner</button></div>}{visible.map(item=><article className={`plannerCard ${plannerStatus(item)}`} key={item.id}>{(item.type==="task"||item.type==="deadline")&&<button className="completeButton" onClick={()=>act(()=>store!.setCompleted(item.id,item.status!=="completed").then(()=>undefined))}>{item.status==="completed"?<CheckCircle2/>:<Check/>}</button>}<div className="plannerCardBody"><div className="plannerCardTop"><span>{item.type}</span><em>{plannerStatus(item)}</em></div><h3>{item.title}</h3><p><Clock3/> {new Intl.DateTimeFormat(locale,{dateStyle:"medium",timeZone:"UTC"}).format(new Date(plannerReferenceDate(item)+"T12:00:00Z"))}</p><div className="plannerCardActions"><button onClick={()=>setReminderItem(item)}><Bell/> Reminder</button><button onClick={()=>setEditing(item)}><Pencil/> Edit</button><button onClick={()=>act(()=>store!.remove(item.id))}><Trash2/> Delete</button></div></div></article>)}</div>}
 {tab==="reminders"&&<div className="reminderPage"><div className="reminderPageHead"><button className="reminderBack" onClick={()=>setTab("today")} aria-label="Back to Planner"><ChevronLeft/></button><div><h2>Reminders</h2><p>All your upcoming reminders and notifications in one place.</p></div></div><div className="reminderPanel"><div className="reminderEnable"><Bell/><div><b>Background notifications</b><span>Enable Web Push on supported signed-in devices.</span></div><button className="button alt" onClick={()=>act(async()=>{await enablePushNotifications();notice("success","Notifications enabled.")})}>Enable</button></div>{!reminders.length&&<div className="plannerEmpty"><Bell/><b>No reminders yet</b></div>}{reminders.map(r=><article className="reminderRow" key={r.id}><div><b>{new Intl.DateTimeFormat(locale,{dateStyle:"medium",timeStyle:"short",timeZone:timezone}).format(new Date(r.scheduledAt))}</b><span>{r.status}</span></div><div className="reminderActions">{r.status!=="handled"&&<button onClick={()=>act(()=>markReminderHandled(r.id))}>Handled</button>}{["pending","sent","failed"].includes(r.status)&&<button onClick={()=>act(()=>snoozeReminder(r.id,15))}>Snooze 15m</button>}{r.status==="pending"&&<button onClick={()=>act(()=>cancelReminder(r.id))}>Cancel</button>}</div></article>)}</div></div>}
 {calendarAction&&<div className="plannerOverlay"><section className="plannerSheet compact calendarActionSheet"><div className="sheetTop"><div><h2>{new Intl.DateTimeFormat(locale,{dateStyle:"long",timeZone:"UTC"}).format(new Date(selectedDate+"T12:00:00Z"))}</h2><span className="sheetHint">What would you like to add?</span></div><button className="iconButton" onClick={()=>setCalendarAction(null)}><X/></button></div><div className="calendarActionChoices"><button onClick={()=>{const i=emptyItem(timezone);i.startDate=selectedDate;i.endDate=selectedDate;i.dueDate=selectedDate;setCalendarAction(null);setEditing(i)}}><CalendarDays/><b>Plan something</b><span>Add an event, task or deadline.</span></button><button onClick={()=>{const i=emptyItem(timezone);i.type="reminder";i.startDate=selectedDate;i.endDate=selectedDate;i.dueDate=selectedDate;i.title="Reminder";setCalendarAction(null);setStandaloneReminder(i)}}><Bell/><b>Set a reminder</b><span>Choose a time and get notified.</span></button></div></section></div>}
 {editing&&<Editor item={editing} busy={busy} onClose={()=>setEditing(null)} onSave={i=>act(async()=>{await store!.upsert(i);setEditing(null);notice("success","Saved to Planner.")})}/>}
 {standaloneReminder&&<Reminder item={standaloneReminder} busy={busy} onClose={()=>setStandaloneReminder(null)} onSave={d=>act(async()=>{await store!.upsert(standaloneReminder);const r=await createReminder(standaloneReminder,d);setStandaloneReminder(null);notice("success",r.backgroundDelivery?"Reminder scheduled.":"Reminder saved on this device.")})}/>}
 {reminderItem&&<Reminder item={reminderItem} busy={busy} onClose={()=>setReminderItem(null)} onSave={d=>act(async()=>{const r=await createReminder(reminderItem,d);setReminderItem(null);notice("success",r.backgroundDelivery?"Reminder scheduled.":"Reminder saved on this device.")})}/>}</section>;
}
function Editor({item,busy,onClose,onSave}:{item:PlannerItem;busy:boolean;onClose:()=>void;onSave:(i:PlannerItem)=>void}){const[d,setD]=useState(item),task=d.type==="task"||d.type==="deadline",patch=(p:Partial<PlannerItem>)=>setD({...d,...p,updatedAt:new Date().toISOString()});return <div className="plannerOverlay"><section className="plannerSheet" role="dialog" aria-modal="true"><div className="sheetTop"><h2>{item.title?"Edit item":"Add to Planner"}</h2><button className="iconButton" onClick={onClose}><X/></button></div><div className="plannerKinds">{(["event","task","deadline","reminder"] as PlannerItemType[]).map(t=><button key={t} className={d.type===t?"active":""} onClick={()=>patch({type:t,startDate:t==="task"||t==="deadline"?"":d.startDate||d.dueDate,dueDate:t==="task"||t==="deadline"?d.dueDate||d.startDate:""})}>{t}</button>)}</div><label><span>Title</span><input value={d.title} onChange={e=>patch({title:e.target.value})}/></label><div className="fieldGrid"><label><span>{task?"Due date":"Start date"}</span><input type="date" value={task?d.dueDate:d.startDate} onChange={e=>patch(task?{dueDate:e.target.value}:{startDate:e.target.value,endDate:d.endDate||e.target.value})}/></label>{!d.allDay&&<label><span>Time</span><input type="time" value={task?d.dueTime:d.startTime} onChange={e=>patch(task?{dueTime:e.target.value}:{startTime:e.target.value})}/></label>}</div><label className="checkLabel"><input type="checkbox" checked={d.allDay} onChange={e=>patch({allDay:e.target.checked})}/> All day</label><label><span>Timezone</span><input value={d.timezone} onChange={e=>patch({timezone:e.target.value})}/></label><label><span>Location</span><input value={d.location} onChange={e=>patch({location:e.target.value})}/></label><label><span>Notes</span><textarea value={d.description} onChange={e=>patch({description:e.target.value})}/></label><button className="button sheetSave" disabled={busy||!d.title.trim()||!(task?d.dueDate:d.startDate)} onClick={()=>onSave(d)}>Save to Planner</button></section></div>;}
function Reminder({item,busy,onClose,onSave}:{item:PlannerItem;busy:boolean;onClose:()=>void;onSave:(d:ReminderDraft)=>void}){
 const[p,setP]=useState<ReminderDraft["preset"]>(item.type==="task"||item.type==="deadline"?"1d":"1h");
 const[custom,setCustom]=useState("");
 const[unit,setUnit]=useState<"minutes"|"hours"|"days">("hours");
 const[time,setTime]=useState("09:00");
 const number=custom.trim()===""?NaN:Number(custom);
 const multiplier=unit==="days"?1440:unit==="hours"?60:1;
 const customMinutes=Number.isFinite(number)?Math.round(number*multiplier):NaN;
 const customValid=p!=="custom"||(Number.isFinite(customMinutes)&&customMinutes>=0&&customMinutes<=525600);
 return <div className="plannerOverlay">
  <section className="plannerSheet compact reminderSheet" role="dialog" aria-modal="true" aria-labelledby="reminder-title">
   <div className="sheetTop"><div><h2 id="reminder-title">Reminder</h2><span className="sheetHint">Choose when Zest should remind you.</span></div><button className="iconButton" onClick={onClose} aria-label="Close reminder"><X/></button></div>
   <div className="reminderChoices">{([["at_time","At time"],["5m","5 min before"],["15m","15 min before"],["30m","30 min before"],["1h","1 hour before"],["1d","1 day before"],["1w","1 week before"],["custom","Custom"]] as [ReminderDraft["preset"],string][]).map(([v,l])=><button type="button" key={v} className={p===v?"active":""} onClick={()=>setP(v)}>{l}</button>)}</div>
   {item.allDay&&<label className="reminderField"><span>Reminder time</span><input type="time" value={time} onChange={e=>setTime(e.target.value)}/></label>}
   {p==="custom"&&<div className="customReminder">
    <label className="reminderField"><span>How long before?</span><input type="number" inputMode="decimal" min="0" step="1" value={custom} placeholder="Enter a number" onChange={e=>setCustom(e.target.value)}/></label>
    <label className="reminderField"><span>Unit</span><select value={unit} onChange={e=>setUnit(e.target.value as "minutes"|"hours"|"days")}><option value="minutes">Minutes</option><option value="hours">Hours</option><option value="days">Days</option></select></label>
   </div>}
   {p==="custom"&&!customValid&&custom.trim()!==""&&<p className="reminderError">Choose a reminder between 0 minutes and 365 days.</p>}
   <button className="button sheetSave" disabled={busy||!customValid} onClick={()=>onSave({preset:p,customMinutes:p==="custom"?customMinutes:undefined,allDayTime:item.allDay?time:undefined})}>Schedule reminder</button>
  </section>
 </div>;
}
