/**
 * iOS home-screen (PWA) startup images. Safari only shows one when its media query matches the device's CSS
 * screen size and pixel ratio exactly, so each supported portrait screen has its own image in public/splash/
 * (generated by `npm run pwa:splash`). Devices not listed show the plain navy background colour instead.
 */
export type StartupScreen = { width: number; height: number; ratio: number; name: string };

export const PWA_STARTUP_SCREENS: StartupScreen[] = [
  // iPhone
  { width: 440, height: 956, ratio: 3, name: "iPhone 16/17 Pro Max" },
  { width: 420, height: 912, ratio: 3, name: "iPhone Air" },
  { width: 402, height: 874, ratio: 3, name: "iPhone 16/17 Pro, 17" },
  { width: 430, height: 932, ratio: 3, name: "iPhone 14 Pro Max, 15 Plus/Pro Max, 16 Plus" },
  { width: 393, height: 852, ratio: 3, name: "iPhone 14 Pro, 15, 15 Pro, 16, 16e" },
  { width: 428, height: 926, ratio: 3, name: "iPhone 12/13 Pro Max, 14 Plus" },
  { width: 390, height: 844, ratio: 3, name: "iPhone 12, 13, 14" },
  { width: 375, height: 812, ratio: 3, name: "iPhone X, XS, 11 Pro, 12/13 mini" },
  { width: 414, height: 896, ratio: 3, name: "iPhone XS Max, 11 Pro Max" },
  { width: 414, height: 896, ratio: 2, name: "iPhone XR, 11" },
  { width: 414, height: 736, ratio: 3, name: "iPhone 6-8 Plus" },
  { width: 375, height: 667, ratio: 2, name: "iPhone 6-8, SE 2/3" },
  { width: 320, height: 568, ratio: 2, name: "iPhone SE 1" },
  // iPad (portrait)
  { width: 1032, height: 1376, ratio: 2, name: "iPad Pro 13 (M4)" },
  { width: 1024, height: 1366, ratio: 2, name: "iPad Pro 12.9" },
  { width: 834, height: 1210, ratio: 2, name: "iPad Pro 11 (M4)" },
  { width: 834, height: 1194, ratio: 2, name: "iPad Pro 11" },
  { width: 820, height: 1180, ratio: 2, name: "iPad Air, iPad 10th gen" },
  { width: 834, height: 1112, ratio: 2, name: "iPad Air 3, Pro 10.5" },
  { width: 810, height: 1080, ratio: 2, name: "iPad 7-9th gen" },
  { width: 768, height: 1024, ratio: 2, name: "iPad mini 5, older iPads" },
  { width: 744, height: 1133, ratio: 2, name: "iPad mini 6/7" },
];

export function startupImageFile(s: StartupScreen) {
  return `zest-splash-${s.width * s.ratio}x${s.height * s.ratio}.png`;
}

/** Entries for Next's `appleWebApp.startupImage` metadata. */
export function pwaStartupImages() {
  return PWA_STARTUP_SCREENS.map((s) => ({
    url: `/splash/${startupImageFile(s)}`,
    media: `(device-width: ${s.width}px) and (device-height: ${s.height}px) and (-webkit-device-pixel-ratio: ${s.ratio}) and (orientation: portrait)`,
  }));
}
