"use client";
import { createClient,isSupabaseConfigured } from "./supabase/client";
import type { PlannerItem,ReminderDraft } from "./planner";
import { calculateReminderAt,reminderMinutes } from "./planner";
// Web Push delivery is handled by the Supabase reminder worker.
export type ReminderRecord={id:string;plannerItemId:string;scheduledAt:string;status:"pending"|"processing"|"sent"|"cancelled"|"failed"|"handled";offsetMinutes?:number;label?:string;deliveredAt?:string;snoozedUntil?:string;handledAt?:string};
const KEY="zest-reminders-v1";function read(s:Storage):ReminderRecord[]{try{const v=JSON.parse(s.getItem(KEY)||"[]");return Array.isArray(v)?v:[];}catch{return[];}}function write(s:Storage,r:ReminderRecord[]){s.setItem(KEY,JSON.stringify(r));}
export async function listReminders(storage=localStorage){if(!isSupabaseConfigured())return read(storage);const db=createClient(),a=await db.auth.getSession();if(!a.data.session?.user||!navigator.onLine)return read(storage);const{data,error}=await db.from("reminders").select("id,planner_item_id,scheduled_at,status,offset_minutes,label,delivered_at,snoozed_until,handled_at").order("scheduled_at",{ascending:true});if(error)throw new Error("Reminders could not be loaded.");return(data||[]).map(r=>({id:r.id,plannerItemId:r.planner_item_id,scheduledAt:r.scheduled_at,status:r.status,offsetMinutes:r.offset_minutes??undefined,label:r.label??undefined,deliveredAt:r.delivered_at??undefined,snoozedUntil:r.snoozed_until??undefined,handledAt:r.handled_at??undefined} as ReminderRecord));}
export async function createReminder(item:PlannerItem,draft:ReminderDraft,label?:string,storage=localStorage){const scheduledAt=calculateReminderAt(item,draft),offset=reminderMinutes(draft);if(!isSupabaseConfigured()){const r:ReminderRecord={id:crypto.randomUUID(),plannerItemId:item.id,scheduledAt,status:"pending",offsetMinutes:offset,label};write(storage,[...read(storage),r]);return{reminder:r,backgroundDelivery:false};}const db=createClient(),a=await db.auth.getSession();if(!a.data.session?.user){const r:ReminderRecord={id:crypto.randomUUID(),plannerItemId:item.id,scheduledAt,status:"pending",offsetMinutes:offset,label};write(storage,[...read(storage),r]);return{reminder:r,backgroundDelivery:false};}if(!navigator.onLine)throw new Error("Connect to the internet to schedule a cloud reminder.");const{data,error}=await db.rpc("create_planner_reminder",{p_item:item.id,p_scheduled_at:scheduledAt,p_offset_minutes:offset,p_label:label||null});if(error)throw new Error("Reminder could not be scheduled.");return{reminder:{id:String(data),plannerItemId:item.id,scheduledAt,status:"pending" as const,offsetMinutes:offset,label},backgroundDelivery:true};}
async function rpc(name:string,args:Record<string,unknown>){if(!isSupabaseConfigured())throw new Error("Cloud reminder action is unavailable.");const{error}=await createClient().rpc(name,args);if(error)throw new Error("Reminder could not be updated.");}
export async function cancelReminder(id:string,storage=localStorage){const l=read(storage);if(l.some(x=>x.id===id)){write(storage,l.map(x=>x.id===id?{...x,status:"cancelled"}:x));return;}await rpc("cancel_planner_reminder",{p_id:id});}
export async function snoozeReminder(id:string,minutes:number,storage=localStorage){const l=read(storage);if(l.some(x=>x.id===id)){if(!Number.isFinite(minutes)||minutes<1||minutes>10080)throw new Error("Choose a snooze between 1 minute and 1 week.");const t=new Date(Date.now()+minutes*60000).toISOString();write(storage,l.map(x=>x.id===id?{...x,status:"pending",scheduledAt:t,snoozedUntil:t}:x));return;}await rpc("snooze_planner_reminder",{p_id:id,p_minutes:minutes});}
export async function markReminderHandled(id:string,storage=localStorage){const l=read(storage);if(l.some(x=>x.id===id)){write(storage,l.map(x=>x.id===id?{...x,status:"handled",handledAt:new Date().toISOString()}:x));return;}await rpc("mark_planner_reminder_handled",{p_id:id});}
export type NotificationState="unsupported"|"blocked"|"available"|"enabled";
export function notificationSupport(){return typeof window!=="undefined"&&"Notification" in window&&"serviceWorker" in navigator&&"PushManager" in window;}
export async function getNotificationState():Promise<NotificationState>{
 if(!notificationSupport())return "unsupported";
 if(Notification.permission==="denied")return "blocked";
 if(Notification.permission!=="granted")return "available";
 try{
  const reg=await navigator.serviceWorker.ready;
  const sub=await reg.pushManager.getSubscription();
  return sub?"enabled":"available";
 }catch{return "available";}
}
function key(v:string){const p="=".repeat((4-v.length%4)%4),b=(v+p).replace(/-/g,"+").replace(/_/g,"/"),raw=atob(b);return Uint8Array.from([...raw].map(c=>c.charCodeAt(0)));}
export async function enablePushNotifications(){if(!notificationSupport())throw new Error("Push notifications are not supported on this device/browser.");if(!isSupabaseConfigured())throw new Error("Sign in to enable background reminders.");const pub=process.env.NEXT_PUBLIC_VAPID_PUBLIC_KEY||"BLfn6Z34FtBgi3t9IqHP9gtUjk9RXxoh7Msm7r8YDdj-_8v8V8Tv1KZJyqVAPrhRygU3MRWaKE-Zvv84JFI-Ekw";if(await Notification.requestPermission()!=="granted")throw new Error("Notification permission was not granted.");const reg=await navigator.serviceWorker.ready,sub=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:key(pub)}),json=sub.toJSON(),db=createClient(),a=await db.auth.getUser();if(!a.data.user)throw new Error("Sign in to enable background reminders.");const{error}=await db.rpc("register_push_subscription",{p_endpoint:sub.endpoint,p_keys:json.keys||{}});if(error)throw new Error("Notification subscription could not be saved.");return true;}
